#! /bin/sh

xsetroot -cursor_name left_ptr &
sxhkd &
# picom --config ~/.config/picom/picom.conf &
picom &
nitrogen --restore &
$HOME/.config/polybar/launch.sh &

pgrep -x sxhkd > /dev/null || sxhkd &

#### MONITORS/DISPLAY PORTS ####
bspc monitor -d       

#### BSPWM configuration ####
# bspc config border_radius                 8
bspc config border_width                  2
bspc config window_gap                    14
bspc config top_padding                   0 # open up space for status bar
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            false
bspc config gapless_monocle               false # empty spaces are gone when in monocle mode
bspc config focus_by_distance             true
bspc config focus_follows_pointer         false # sloppy focus follow cursor
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a mplayer2 state=floating

### ________________________________ ###
###|        Gruvbox palette         |###
###|--------------------------------|###
###| bg      = #282828              |###
###| red     = #cc241d              |###
###| green   = #98971a              |###
###| yellow  = #d79921              |###
###| blue    = #458588              |###
###| purple  = #b16286              |###
###| aqua    = #689d6a              |###
###| gray    = #a89984              |###
###| fg      = #ebdbb2              |###
###|                                |###
###| bg0_h   = #1d2021              |###
###| bg0     = #282828              |###
###| bg1     = #3c3836              |###
###| bg2     = #504945              |###
###| bg3     = $665c54              |###
###| bg4     = #7c6f64              |###
###| gray1   = #928374              |###
###| orange  = #d65d0e              |###
###|                                |###
###| bg0_s   = #32302f              |###
###| fg4     = #a89984              |###
###| fg3     = #bdae93              |###
###| fg2     = #d5c4a1              |###
###| fg1     = #ebdbb2              |###
###| fg0     = #fbf1c7              |###
###| orange1 = #fe8019              |###
###|________________________________|###


bspc config normal_border_color		      "#1d2021" # bg0_h
bspc config active_border_color	          "#1d2021" # bg0_h
bspc config focused_border_color	      "#689d6a" # green
bspc config presel_feedback_color	      "#689d6a" # yellow
bspc config urgent_border_color 	      "#b16286" # purple

# other apps are managed through the script bellow
./autorun.sh
