theme = "catppuccin_mocha"

[editor]
bufferline = "always"
true-color = true
rulers = [80]
line-number = "relative"

[keys.normal]
C-h = [":buffer-previous"]
C-l = [":buffer-next"]
C-x = [":buffer-close"]

