#! /bin/sh

xsetroot -cursor_name left_ptr &
sxhkd &
# picom --config ~/.config/picom/picom.conf &
picom &
nitrogen --restore &
$HOME/.config/polybar/launch.sh &

xautolock -time 10 -corners +00- -locker "$HOME/.config/i3lock/i3lock.sh" &

pgrep -x sxhkd > /dev/null || sxhkd &

#### MONITORS/DISPLAY PORTS ####
bspc monitor -d 1 2 3 4 5 6 7

#### BSPWM configuration ####
# bspc config border_radius                 8
bspc config border_width                  2
bspc config window_gap                    10
bspc config top_padding                   0 # open up space for status bar
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            false
bspc config gapless_monocle               false # empty spaces are gone when in monocle mode
bspc config focus_by_distance             true
bspc config focus_follows_pointer         false # sloppy focus follow cursor
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a mplayer2 state=floating

bspc config normal_border_color		      "#000000"
bspc config active_border_color	          "#000000"
bspc config focused_border_color	      "#fefefe"
bspc config presel_feedback_color	      "#fefefe"
bspc config urgent_border_color 	      "#ed8796"

# other apps are managed through the script bellow
./autorun.sh
