#! /bin/sh

xsetroot -cursor_name left_ptr &
sxhkd &
picom --config ~/.config/picom/picom.conf &
nitrogen --restore &
$HOME/.config/polybar/launch.sh &

pgrep -x sxhkd > /dev/null || sxhkd &


#### MONITORS/DISPLAY PORTS ####
bspc monitor -d ○ ○ ○ ○ ○ ○

#### BSPWM configuration ####
# bspc config border_radius                 8
bspc config border_width                  2
bspc config window_gap                    14
bspc config top_padding                   0 # open up space for status bar
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               false # empty spaces are gone when in monocle mode
bspc config focus_by_distance             true
bspc config focus_follows_pointer         false # sloppy focus follow cursor
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#### BSPWM coloring                 ####

####        Current color scheme:   ####
#### primary         '#20242C'      ####
#### secondary       '#CF6F91'      ####
#### urgent          '#629AC4'      ####
#### accent          '#74536D'      ####
#### text            '#efd6ac'      ####


bspc config normal_border_color		      "#20242C" # primary
bspc config active_border_color	          "#20242C" # primary
bspc config focused_border_color	      "#CF6F91" # secondary
bspc config presel_feedback_color	      "#74536D" # accent
bspc config urgent_border_color 	      "#629AC4" # urgent

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out thHe name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)
