;### ________________________________ ###
;###|         BSPWM coloring         |###
;###|--------------------------------|###
;###|      Current color scheme:     |###
;###| primary         '#0d1117'      |###
;###| secondary       '#CF6F91'      |###
;###| urgent          '#629AC4'      |###
;###| accent          '#74536D'      |###
;###| text            '#efd6ac'      |###
;###|________________________________|###

;----------------------------------------------
; COLORS FROM MY BSPWM CONFIG

[color]

primary   = #0d1117
secondary = #CF6F91
urgent    = #629AC4
accent    = #74536D

; had to change, the color originaly used looked kinda weird...
text      = #d6d6d6
disabled  = #20242C ; do not remove this comment; it is here to force the bg color to default

background = #0d1117
background-alt = #373B41
module-background = #0d1117

; text
foreground = #C5C8C6
