include-file = $HOME/.config/polybar/colors.ini
include-file = $HOME/.config/polybar/sizes.ini

;----------------------------------------------
; OTHER VALUES

; none so far :D

;----------------------------------------------
; global configs

[global/wm]
margin-top = 5
margin-bottom = -5

;----------------------------------------------
; bar setup

[bar/main]
width  = ${sizes.bar-width}
height = ${sizes.bar-height}
radius = ${sizes.bar-radius}

offset-x = ${sizes.bar-offset-x}

background = #00000000
foreground = ${color.text}

line-size = ${sizes.line-size}

border-size  = ${sizes.border-size}
border-color = #00000000

padding-left  = ${sizes.padding-left}
padding-right = ${sizes.padding-right}

module-margin = ${sizes.module-margin}

font-0 = "Roboto:size=12;2"
font-1 = "FiraCode Nerd Font:style=Medium:size=20;5"

; sets up systray on the left side
; tray-position   = left
tray-background = ${color.primary}

; bar order
modules-left = rightborder xwindow leftborder
modules-center = rightborder xworkspaces leftborder
modules-right = rightborder alsamixer sep memory sep cpu sep wlan sep date leftborder

; cursor
cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; disable polybar on fullscreen for bspwm
wm-restack = bspwm

;----------------------------------------------
; round borders

[glyph]
gleft = 
gright = 

[module/leftborder]
type = custom/text
content-background = #002d333f
content-foreground = ${color.background}
content = ${glyph.gleft}
content-font = 2

[module/rightborder]
type = custom/text
content-background = #002d333f
content-foreground = ${color.background}
content = ${glyph.gright}
content-font = 2

[module/sep]
type = custom/text
content = "    "

content-foreground = ${color.background}
content-background = ${color.background}

;----------------------------------------------
; workspaces

[module/xworkspaces]
type = internal/xworkspaces
format-background = ${color.background}

; active/selected
label-active = ●
label-active-underline  = ${color.secondary}
label-active-padding    = ${sizes.label-padding}
label-active-foreground = ${color.secondary}

; occupied
label-occupied = %name%
label-occupied-padding    = ${sizes.label-padding}
label-occupied-foreground = ${color.accent}

; urgent
label-urgent = %name%
label-urgent-padding    = ${sizes.label-padding}
label-urgent-foreground = ${color.urgent}

; empty
label-empty = %name%
label-empty-padding    = ${sizes.label-padding}
label-empty-foreground = ${color.secondary}

;----------------------------------------------
; focused window/client info

[module/xwindow]
type = internal/xwindow
label = %title:0:40:...%
format-background = ${color.background}
label-underline = ${color.secondary}

;----------------------------------------------
; volume info

[module/alsamixer]
type = internal/pulseaudio

format-volume-background        = ${color.background}
format-volume-prefix            = "vol "
format-volume-prefix-underline  = ${color.secondary}
format-volume-prefix-foreground = ${color.secondary}
format-volume                   = <label-volume>

label-volume           = %percentage%%
label-volume-underline = ${color.secondary}

format-muted-background = ${color.background}
label-muted             = muted
label-muted-foreground  = ${color.disabled}
label-muted-underline   = ${color.accent}

;----------------------------------------------
; memory use

[module/memory]
type             = internal/memory
interval         = 2
format-background = ${color.background}
format-underline = ${color.secondary}

format-prefix            = "ram "
format-prefix-foreground = ${color.secondary}

label = %percentage_used:2%%

;----------------------------------------------
; cpu use

[module/cpu]
type     = internal/cpu
interval = 2

format-background = ${color.background}
format-prefix            = "cpu "
format-underline         = ${color.secondary}
format-prefix-foreground = ${color.secondary}

label = %percentage:2%%

;----------------------------------------------
; wired connection

[network-base]
type = internal/network
interval = 5

format-connected-background = ${color.background}
format-connected = <label-connected>
label-connected-underline  = ${color.secondary}

format-disconnected-background = ${color.background}
format-disconnected = <label-disconnected>
label-disconnected = %{F#CF6F91}%ifname%%{F#707880} disconnected
label-disconnected-underline  = ${color.accent}

;----------------------------------------------
; wireless connection

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{F#CF6F91}%ifname%%{F-} %essid%

;----------------------------------------------
; date and time

[module/date]
type = internal/date
interval = 1

format-background = ${color.background}
format-underline  = ${color.secondary}

date = %H:%M
date-alt = %Y-%m-%d %H:%M:%S

label = %date%
label-foreground = ${color.secondary}

;----------------------------------------------
; bottom bar

[bar/bottom]
bottom = true

fixed-center = true
padding      = 0
width        = ${sizes.bottom-bar-width}
height       = ${sizes.bottom-bar-height}
; offset-x     = ${sizes.bottom-bar-height}
radius       = ${sizes.bar-radius}

background = #00000000
foreground = ${color.foreground}
dim-value = 1.0

cursor-click = pointer

line-size = ${sizes.line-size}
line-color = ${color.background}

font-0 = "FiraCode Nerd Font:size=10;2"
font-1 = "FiraCode Nerd Font:style=Medium:size=20;5"
tray-position = right
tray-detached = false
tray-maxsize = 16
tray-background = #002d333f
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 0
tray-scale = 1.0

enable-ipc = true

;----------------------------------------------
; other settings

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini